USE transmetro_db;
CREATE TABLE IF NOT EXISTS piloto_bus (
 id_piloto INT UNSIGNED PRIMARY KEY,
 id_bus INT UNSIGNED NOT NULL,
 CONSTRAINT fk_piloto_bus_piloto FOREIGN KEY (id_piloto) REFERENCES pilotos(id_piloto) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CONSTRAINT fk_piloto_bus_bus FOREIGN KEY (id_bus) REFERENCES buses(id_bus) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB;
