type Step={title:string;description:string;page:string};
const guides:Record<string,{intro:string;steps:string[];tip:string}>={
 routes:{intro:'Una ruta es el camino que siguen los buses. Un recorrido es un viaje concreto por esa ruta.',steps:['Crea la ruta como inactiva para prepararla.','Agrega estaciones en el orden en que las visitará el bus.','Asigna buses y activa la ruta. Después programa sus viajes en Recorridos.'],tip:'Si no puedes editar las paradas, revisa los recorridos pendientes. Debes finalizarlos o cancelarlos antes de cambiar la ruta.'},
 stations:{intro:'Organiza los lugares donde suben y bajan los pasajeros.',steps:['Registra el nombre, código y capacidad de la estación.','Asígnala a una ruta y define su posición.','Actualiza los pasajeros esperando para conocer el aforo.'],tip:'Capacidad es el máximo de personas; aforo actual es cuántas están esperando en este momento.'},
 fleet:{intro:'Cada bus tiene su propia cantidad de asientos y una ruta asignada.',steps:['Agrega código, placa y número de asientos del bus.','Selecciona su línea y el parqueo donde se guarda.','Usa Editar asientos o Cambiar asignación cuando no tenga recorridos pendientes.'],tip:'Puedes tener buses de 20, 32 o 50 asientos. El mapa de abordaje se adapta a cada unidad.'},
 trips:{intro:'Programa cada salida con un bus, un piloto y un horario en Guatemala.',steps:['Elige Programar recorrido y selecciona bus y piloto.','Indica fecha, hora de salida y fecha y hora de llegada estimada.','Abre el recorrido para registrar llegadas, abordar pasajeros e iniciar el viaje.'],tip:'La ruta se toma del bus seleccionado. Si un horario se cruza con otro del mismo bus o piloto, el sistema te pedirá corregirlo.'},
 boarding:{intro:'Elige un recorrido y registra a cada pasajero en un asiento disponible.',steps:['Selecciona el recorrido y un asiento marcado como disponible.','Elige pasajero, estación de ingreso, destino y método de pago.','Emite el ticket o reserva el asiento. Registra las llegadas y salidas de cada estación.'],tip:'Reservar aparta temporalmente el asiento; emitir registra el ticket y su pago. Los colores se explican encima del mapa.'},
 finance:{intro:'Consulta tarjetas y registra las recargas de los pasajeros.',steps:['Selecciona la tarjeta que recibirá el saldo.','Indica el monto y el método de pago.','Confirma la recarga y consulta el movimiento en Reportes.'],tip:'Revisa el número de tarjeta antes de guardar una recarga.'},
 catalogs:{intro:'Aquí mantienes la información que utilizan las demás pantallas.',steps:['Selecciona el tipo de información en la lista de catálogos.','Busca un registro existente o elige Nuevo registro.','Completa los campos obligatorios y guarda.'],tip:'Para estaciones, rutas y buses también tienes pantallas propias en el menú.'},
 reports:{intro:'Consulta los movimientos guardados durante la operación.',steps:['Selecciona el reporte que necesitas.','Revisa los registros y utiliza la búsqueda disponible.','Descarga CSV para trabajar con los datos en una hoja de cálculo.'],tip:'La bitácora permite al administrador revisar quién realizó cambios.'},
 users:{intro:'Crea accesos para las personas que trabajarán en el sistema.',steps:['Registra un usuario y una contraseña.','Selecciona los roles según las tareas de la persona.','Si es piloto, vincula su ficha antes de guardar.'],tip:'Los roles determinan qué pantallas y acciones puede usar cada persona.'}
};
export function PageGuide({page,roles,onGo}:{page:string;roles:string[];onGo:(page:string)=>void}){
 const has=(...r:string[])=>roles.some(role=>r.includes(role));
 if(page==='dashboard'){
 const actions:Step[]=has('ADMINISTRADOR','SUPERVISOR')?[
 {title:'Preparar la red',description:'Revisa las estaciones y el orden de las rutas.',page:'routes'},
 {title:'Organizar las salidas',description:'Asigna un bus, piloto y horario a cada viaje.',page:'trips'},
 {title:'Atender pasajeros',description:'Selecciona asientos y registra tickets.',page:'boarding'}
 ]:has('OPERADOR','PILOTO')?[{title:'Consultar mis recorridos',description:'Encuentra el viaje que vas a atender.',page:'trips'},{title:'Abrir el abordaje',description:has('OPERADOR')?'Consulta asientos y registra pasajeros.':'Consulta los asientos y el estado del viaje.',page:'boarding'}]:has('FINANCIERO')?[{title:'Gestionar recargas',description:'Consulta tarjetas y registra saldo.',page:'finance'},{title:'Revisar movimientos',description:'Consulta pagos y recargas.',page:'reports'}]:[{title:'Revisar estaciones',description:'Consulta la red y gestiona accesos.',page:'stations'},{title:'Consultar alertas',description:'Revisa incidencias de la operación.',page:'reports'}];
 return <section className="start-guide" aria-label="Acciones para comenzar"><div><span className="eyebrow">TU PRÓXIMO PASO</span><h2>¿Qué necesitas hacer?</h2><p>Elige una tarea. En cada pantalla encontrarás una guía breve.</p></div><div className="guide-actions">{actions.map((a,i)=><button key={a.page} onClick={()=>onGo(a.page)}><span className="guide-number">{i+1}</span><strong>{a.title}</strong><span>{a.description}</span><b aria-hidden="true">→</b></button>)}</div></section>
 }
 const guide=guides[page];if(!guide)return null;
 return <details key={page} className="page-guide"><summary><span className="guide-question" aria-hidden="true">?</span><span>Cómo usar esta pantalla<small>{guide.intro}</small></span><span className="guide-expand" aria-hidden="true">+</span></summary><div className="guide-body"><ol>{guide.steps.map(step=><li key={step}>{step}</li>)}</ol><p><strong>Ten en cuenta:</strong> {guide.tip}</p></div></details>
}
