import {useEffect,useState} from 'react';
import {api} from './api';
type Row=Record<string,any>;
export function Pilots({admin,onChange,onUsers,onTrips}:{admin:boolean;onChange:()=>void;onUsers:()=>void;onTrips:()=>void}){
 const [rows,setRows]=useState<Row[]>([]),[buses,setBuses]=useState<Row[]>([]),[lines,setLines]=useState<Row[]>([]),[edit,setEdit]=useState<Row|null>(null),[assign,setAssign]=useState<Row|null>(null),[filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[busId,setBusId]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 async function load(){const [p,b,l]=await Promise.all([api('pilotos'),api('buses'),api('catalogos/lineas')]);setRows(p);setBuses(b);setLines(l)}
 useEffect(()=>{load().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 async function save(fn:()=>Promise<any>){setBusy(true);setError('');setNotice('');try{await fn();await load();setAssign(null);setEdit(null);onChange();setNotice('Datos guardados correctamente.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const route=(b:Row)=>lines.find(l=>l.id_linea===b.bus_linea_historial[0]?.id_linea);
 const selected=buses.find(b=>String(b.id_bus)===busId);
 const visible=rows.filter(p=>`${p.nombres} ${p.apellidos} ${p.bus_codigo??''} ${p.ruta_nombre??''}`.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||(filter==='unassigned'&&!p.id_bus)||(filter==='ready'&&p.estado&&p.id_bus&&p.bus_estado==='ACTIVO'&&p.ruta_activa)));
 return <section className="panel management-panel"><div className="panel-heading"><div><h2>Pilotos y asignaciones</h2><p>Registra al piloto, asigna su bus y luego programa sus salidas.</p></div>{admin&&<button className="primary" onClick={()=>{setEdit({});setAssign(null)}}>+ Registrar piloto</button>}</div><div className="workflow-guide"><h3>Un conductor y su cuenta son cosas distintas</h3><p>Aquí registras quién conduce y qué bus utiliza. Solo crea una cuenta de usuario si necesita entrar al sitio.</p><ol><li><strong>Registra al piloto</strong><span>Nombre y apellidos son obligatorios.</span></li><li><strong>Asigna su bus</strong><span>La ruta se obtiene de la unidad elegida.</span></li><li><strong>Programa una salida</strong><span>Elige fecha y horario en Recorridos.</span></li></ol></div>{error&&<p className="error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {edit&&<form key={edit.id_piloto??'new'} className="catalog-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const data=Object.fromEntries(['nombres','apellidos','dpi','residencia','telefono','correo'].map(k=>[k,String(f.get(k)??'').trim()||null]));void save(()=>api('catalogos/pilotos'+(edit.id_piloto?'/'+edit.id_piloto:''),edit.id_piloto?'PATCH':'POST',{...data,estado:Number(f.get('estado'))}))}}><h3>{edit.id_piloto?'Editar piloto':'Nuevo piloto'}</h3><div className="form-grid">{[['nombres','Nombres',100],['apellidos','Apellidos',100],['dpi','DPI',20],['residencia','Residencia',150],['telefono','Teléfono',20],['correo','Correo',120]].map(([key,label,max])=><label key={key}>{label}<input name={String(key)} type={key==='correo'?'email':'text'} maxLength={Number(max)} required={key==='nombres'||key==='apellidos'} defaultValue={edit[String(key)]??''}/></label>)}<label>Estado<select name="estado" defaultValue={Number(edit.estado??true)}><option value="1">Activo</option><option value="0">Inactivo</option></select></label></div><button className="primary" disabled={busy}>Guardar piloto</button><button type="button" className="secondary" disabled={busy} onClick={()=>setEdit(null)}>Cancelar</button></form>}
 {assign&&<form className="catalog-form" onSubmit={e=>{e.preventDefault();void save(()=>api(`pilotos/${assign.id_piloto}/asignar`,'POST',{id_bus:Number(busId)}))}}><h3>Asignar bus a {assign.nombres} {assign.apellidos}</h3><label>Bus y ruta<select value={busId} onChange={e=>setBusId(e.target.value)} required><option value="">Seleccionar bus…</option>{buses.filter(b=>b.estado==='ACTIVO'&&route(b)?.estado).map(b=><option key={b.id_bus} value={b.id_bus}>{b.codigo} · {b.placa} · {route(b)?.nombre}</option>)}</select></label>{!buses.some(b=>b.estado==='ACTIVO'&&route(b)?.estado)&&<p role="status">No hay buses disponibles con ruta activa. Primero configura la unidad en Flota de buses y activa su ruta.</p>}<p>Ruta asignada: <strong>{selected?route(selected)?.nombre:'Selecciona un bus'}</strong></p><p className="muted">La ruta se toma del bus. Varios pilotos pueden trabajar en la misma unidad en horarios distintos; el sistema valida los cruces de horario al programar.</p><button className="primary" disabled={busy||!selected||!route(selected)?.estado}>Guardar asignación</button><button className="secondary" type="button" disabled={busy} onClick={()=>setAssign(null)}>Cancelar</button></form>}
 <div className="station-tools"><label>Mostrar<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos los pilotos</option><option value="unassigned">Pendientes de asignar bus</option><option value="ready">Con bus y ruta activos</option></select></label><label>Buscar piloto, bus o ruta<input placeholder="Nombre, código de bus o ruta" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>{loading?<p>Cargando pilotos…</p>:<div className="station-grid">{visible.map(p=><article className="station-card" key={p.id_piloto}><h3>{p.nombres} {p.apellidos}</h3><p>{p.estado?'Activo':'Inactivo'}</p><p>Bus: <strong>{p.bus_codigo??'Sin asignar'}</strong></p><p>Ruta: {p.ruta_nombre??'Sin asignar'}</p>{p.id_bus&&(p.bus_estado!=='ACTIVO'||!p.ruta_activa)&&<p className="error">Revisa la disponibilidad del bus o la ruta antes de programar.</p>}<div className="row-actions"><button className="primary" disabled={!p.estado} onClick={()=>{setAssign(p);setBusId(String(p.id_bus??''));setEdit(null)}}>{p.id_bus?'Cambiar bus':'Asignar bus y ruta'}</button>{!!p.estado&&!!p.id_bus&&p.bus_estado==='ACTIVO'&&!!p.ruta_activa&&<button className="secondary" onClick={onTrips}>Programar salida →</button>}{admin&&<button className="secondary" onClick={()=>{setEdit(p);setAssign(null)}}>Editar piloto</button>}</div></article>)}</div>}
 {!loading&&rows.length>0&&!visible.length&&<p>No hay coincidencias. Prueba otro nombre o cambia el filtro.</p>}{admin&&<div className="next-step"><div><strong>¿El piloto necesita iniciar sesión?</strong><p>Crea una cuenta con rol PILOTO y vincula su ficha. Es opcional para registrar sus viajes.</p></div><button className="secondary" onClick={onUsers}>Ir a cuentas de acceso →</button></div>}{!loading&&!rows.length&&<p>No hay pilotos registrados. El administrador debe registrar el primero.</p>}</section>
}
