import {useEffect,useState} from 'react';
import {api} from './api';
type Row=Record<string,any>;
export function Routes({roles,onChange,onStations,onFleet,onTrips}:{roles:string[],onChange:()=>void,onStations:()=>void,onFleet:()=>void,onTrips:()=>void}){
 const [lines,setLines]=useState<Row[]>([]),[stations,setStations]=useState<Row[]>([]),[links,setLinks]=useState<Row[]>([]),[buses,setBuses]=useState<Row[]>([]),[trips,setTrips]=useState<Row[]>([]);
 const [selected,setSelected]=useState(''),[query,setQuery]=useState(''),[edit,setEdit]=useState<Row|null>(null),[stop,setStop]=useState<Row|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const admin=roles.includes('ADMINISTRADOR');
 async function load(){const [l,s,a,b,t]=await Promise.all([api('catalogos/lineas'),api('catalogos/estaciones'),api('catalogos/linea_estacion'),api('buses'),api('recorridos')]);setLines(l);setStations(s);setLinks(a);setBuses(b);setTrips(t);setSelected(prev=>prev||String(l[0]?.id_linea??''));}
 useEffect(()=>{load().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 async function save(fn:()=>Promise<any>,message:string){setBusy(true);setError('');setNotice('');try{const result=await fn();await load();onChange();setNotice(message);return result}catch(e:any){setError(e.message);return null}finally{setBusy(false)}}
 const line=lines.find(l=>String(l.id_linea)===selected),ordered=links.filter(l=>String(l.id_linea)===selected).sort((a,b)=>a.orden-b.orden),assigned=buses.filter(b=>b.bus_linea_historial.some((a:Row)=>String(a.id_linea)===selected));
 const pending=trips.filter(t=>String(t.id_linea)===selected&&['PROGRAMADO','EN_CURSO'].includes(t.estado));
 const matches=lines.filter(l=>`${l.codigo} ${l.nombre}`.toLowerCase().includes(query.toLowerCase()));
 return <section className="panel management-panel"><div className="panel-heading"><div><h2>Rutas y líneas</h2><p>Estaciones ordenadas y flota asignada a cada línea</p></div>{admin&&<button className="primary" onClick={()=>{setEdit({});setStop(null)}}>+ Nueva ruta</button>}</div>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {edit&&<form className="catalog-form" key={edit.id_linea??'new'} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const id=edit.id_linea;const row=await save(()=>api('catalogos/lineas'+(id?'/'+id:''),id?'PATCH':'POST',{codigo:String(f.get('codigo')).trim(),nombre:String(f.get('nombre')).trim(),descripcion:String(f.get('descripcion')).trim()||null,estado:Number(f.get('estado'))}),'Ruta guardada.');if(row){setSelected(String(row.id_linea));setEdit(null)}}}><h3>{edit.id_linea?'Editar ruta':'Nueva ruta'}</h3><div className="form-grid"><label>Código<input name="codigo" required maxLength={20} defaultValue={edit.codigo}/></label><label>Nombre<input name="nombre" required maxLength={100} defaultValue={edit.nombre}/></label><label>Descripción<input name="descripcion" maxLength={200} defaultValue={edit.descripcion??''}/></label><label>Estado<select name="estado" defaultValue={Number(edit.estado??false)}><option value="0">Inactiva · en preparación</option><option value="1">Activa</option></select></label></div><p className="muted">Prepara la ruta inactiva: agrega sus estaciones y asigna entre uno y dos buses por estación antes de activarla.</p><div className="row-actions"><button disabled={busy} className="primary">Guardar ruta</button><button type="button" className="secondary" onClick={()=>setEdit(null)}>Cancelar</button></div></form>}
 <div className="station-tools"><label>Buscar ruta<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Código o nombre"/></label><label>Ruta<select value={selected} onChange={e=>{setSelected(e.target.value);setStop(null);setEdit(null)}}><option value="">Seleccionar…</option>{lines.filter(l=>String(l.id_linea)===selected||matches.includes(l)).map(l=><option value={l.id_linea} key={l.id_linea}>{l.codigo} · {l.nombre}</option>)}</select></label></div>
 {query&&<div className="row-actions" aria-label="Resultados de búsqueda">{matches.length?matches.map(l=><button className="secondary" key={l.id_linea} onClick={()=>{setSelected(String(l.id_linea));setStop(null);setEdit(null)}}>{l.codigo} · {l.nombre}</button>):<p>No hay rutas que coincidan con la búsqueda.</p>}</div>}
 {loading?<p>Cargando rutas…</p>:!line?<p>Selecciona o registra una ruta.</p>:<><div className="panel-heading"><div><h3>{line.nombre}</h3><p>{line.descripcion}</p><span className="badge">{line.estado?'Activa':'Inactiva'}</span></div>{admin&&<button className="secondary" onClick={()=>{setEdit(line);setStop(null)}}>Editar ruta</button>}</div><p>{ordered.length} estaciones · {assigned.length} buses · {ordered.reduce((sum,s)=>sum+Number(s.distancia_anterior_km??0),0).toFixed(2)} km registrados</p><div className="row-actions">{admin&&<button className="primary" disabled={pending.length>0} onClick={()=>{setStop({orden:(ordered.at(-1)?.orden??0)+1});setEdit(null)}}>+ Agregar estación</button>}<button className="secondary" onClick={onStations}>Gestionar estaciones</button><button className="secondary" onClick={onFleet}>Asignar buses</button><button className="secondary" onClick={onTrips}>Ver recorridos</button></div><p className="muted">Origen: {stations.find(s=>s.id_estacion===ordered[0]?.id_estacion)?.nombre??'Sin definir'} · Destino: {stations.find(s=>s.id_estacion===ordered.at(-1)?.id_estacion)?.nombre??'Sin definir'}</p>{pending.length>0&&<p role="status">Esta ruta tiene {pending.length} recorridos pendientes entre los 200 más recientes. Finalízalos o cancélalos en Recorridos para editar sus paradas.</p>}
 {stop&&<form className="catalog-form" key={selected+'-'+(stop.id_estacion??'new')} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const stationId=stop.id_estacion??Number(f.get('id_estacion'));const result=await save(()=>api('catalogos/linea_estacion'+(stop.id_estacion?`/${selected}~${stationId}`:''),stop.id_estacion?'PATCH':'POST',{id_linea:Number(selected),id_estacion:stationId,orden:Number(f.get('orden')),distancia_anterior_km:Number(f.get('distancia'))}),'Estación de la ruta guardada.');if(result)setStop(null)}}><h3>{stop.id_estacion?'Editar parada':'Agregar estación'}</h3><div className="form-grid"><label>Estación<select name="id_estacion" required disabled={!!stop.id_estacion} defaultValue={stop.id_estacion??''}><option value="">Seleccionar…</option>{stations.filter(s=>s.id_estacion===stop.id_estacion||(s.estado&&!ordered.some(o=>o.id_estacion===s.id_estacion))).map(s=><option key={s.id_estacion} value={s.id_estacion}>{s.codigo} · {s.nombre}</option>)}</select></label><label>Orden<input name="orden" type="number" min="1" step="1" required defaultValue={stop.orden}/></label><label>Distancia desde la anterior (km)<input name="distancia" type="number" min="0" max="999999.99" step="0.01" required defaultValue={stop.distancia_anterior_km??0}/></label></div><p className="muted">El orden debe estar libre. Finaliza o cancela los recorridos pendientes antes de modificar las paradas.</p><div className="row-actions"><button className="primary" disabled={busy}>Guardar parada</button><button type="button" className="secondary" onClick={()=>setStop(null)}>Cancelar</button></div></form>}
 <ol className="route-stations">{ordered.map(s=><li key={s.id_estacion}><strong>{s.orden}. {stations.find(x=>x.id_estacion===s.id_estacion)?.nombre??'Estación '+s.id_estacion}</strong><span>{Number(s.distancia_anterior_km??0).toFixed(2)} km desde la anterior</span>{admin&&<button className="text-button" disabled={pending.length>0} onClick={()=>{setStop(s);setEdit(null)}}>Editar orden y distancia</button>}</li>)}</ol>{!ordered.length&&<p>Esta ruta todavía no tiene estaciones.</p>}<h3>Buses asignados</h3><div className="station-grid">{assigned.map(b=><div className="station-card" key={b.id_bus}><strong>{b.codigo}</strong><p>Placa {b.placa} · {b.capacidad_maxima} asientos</p><span className="badge">{b.estado}</span></div>)}</div>{!assigned.length&&<p>Asigna buses a esta ruta desde Flota de buses.</p>}</>}
 </section>
}
