import {useEffect,useState} from 'react';
import {api} from './api';
type Row=Record<string,any>;
export function Stations({roles,onCatalog,onChange}:{roles:string[],onCatalog:(name:string)=>void,onChange:()=>void}){
 const [stations,setStations]=useState<Row[]>([]),[lines,setLines]=useState<Row[]>([]),[links,setLinks]=useState<Row[]>([]);
 const [query,setQuery]=useState(''),[status,setStatus]=useState('all'),[edit,setEdit]=useState<Row|null>(null),[assign,setAssign]=useState<Row|null>(null);
 const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const admin=roles.includes('ADMINISTRADOR'),canCount=roles.some(r=>['ADMINISTRADOR','SUPERVISOR','OPERADOR'].includes(r));
 async function load(){const [s,l,a]=await Promise.all(['estaciones','lineas','linea_estacion'].map(n=>api('catalogos/'+n)));setStations(s);setLines(l);setLinks(a);}
 useEffect(()=>{load().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 async function save(action:()=>Promise<unknown>,message:string){setBusy(true);setError('');setNotice('');try{await action();await load();onChange();setNotice(message);return true}catch(e:any){setError(e.message);return false}finally{setBusy(false)}}
 const visible=stations.filter(s=>(status==='all'||s.estado===(status==='active'))&&`${s.codigo} ${s.nombre}`.toLowerCase().includes(query.toLowerCase()));
 return <section className="panel management-panel"><div className="panel-heading"><div><h2>Estaciones de la red</h2><p>Capacidad y pasajeros en espera por estación</p></div>{admin&&<button className="primary" onClick={()=>{setEdit({});setAssign(null)}}>+ Registrar estación</button>}</div>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <div className="station-tools"><label>Buscar estación<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Código o nombre"/></label><label>Estado<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todas</option><option value="active">Activas</option><option value="inactive">Inactivas</option></select></label><button className="secondary" disabled={busy} onClick={()=>save(async()=>{},'Estaciones actualizadas.')}>Actualizar</button></div>
 {edit&&<form className="catalog-form" key={edit.id_estacion??'new'} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const id=edit.id_estacion;const ok=await save(()=>api('catalogos/estaciones'+(id?'/'+id:''),id?'PATCH':'POST',{codigo:String(f.get('codigo')).trim(),nombre:String(f.get('nombre')).trim(),capacidad_maxima:Number(f.get('capacidad_maxima')),estado:Number(f.get('estado'))}),'Estación guardada.');if(ok)setEdit(null)}}><h3>{edit.id_estacion?'Editar estación':'Nueva estación'}</h3><div className="form-grid"><label>Código<input name="codigo" maxLength={20} required defaultValue={edit.codigo}/></label><label>Nombre<input name="nombre" maxLength={100} required defaultValue={edit.nombre}/></label><label>Capacidad máxima de pasajeros<input name="capacidad_maxima" type="number" min="1" max="100000" step="1" required defaultValue={edit.capacidad_maxima}/></label><label>Estado<select name="estado" defaultValue={Number(edit.estado??true)}><option value="1">Activa</option><option value="0">Inactiva</option></select></label></div><p className="muted">La capacidad indica cuántas personas pueden esperar en la estación.</p><div className="row-actions"><button className="primary" disabled={busy}>Guardar estación</button><button type="button" className="secondary" onClick={()=>setEdit(null)}>Cancelar</button></div></form>}
 {assign&&<form className="catalog-form" key={assign.id_estacion} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const lid=Number(f.get('id_linea'));const existing=links.some(l=>l.id_estacion===assign.id_estacion&&l.id_linea===lid);const ok=await save(()=>api('catalogos/linea_estacion'+(existing?`/${lid}~${assign.id_estacion}`:''),existing?'PATCH':'POST',{id_linea:lid,id_estacion:assign.id_estacion,orden:Number(f.get('orden')),distancia_anterior_km:Number(f.get('distancia'))}),'Asignación guardada.');if(ok)setAssign(null)}}><h3>Asignar {assign.nombre} a una línea</h3><div className="form-grid"><label>Línea<select name="id_linea" required defaultValue=""><option value="">Seleccionar línea…</option>{lines.map(l=><option key={l.id_linea} value={l.id_linea}>{l.codigo} · {l.nombre}</option>)}</select></label><label>Orden en la ruta<input name="orden" type="number" min="1" step="1" required/></label><label>Distancia desde la estación anterior (km)<input name="distancia" type="number" min="0" max="999999.99" step="0.01" defaultValue="0" required/></label></div><p className="muted">Para cambiar una ruta, finaliza o cancela sus recorridos pendientes. Si esta estación ya pertenece a la línea, se actualizará su orden y distancia.</p><div className="row-actions"><button className="primary" disabled={busy}>Guardar asignación</button><button type="button" className="secondary" onClick={()=>setAssign(null)}>Cancelar</button></div></form>}
 {loading?<p>Cargando estaciones…</p>:<><p className="muted">{visible.length} estaciones · {stations.filter(s=>s.estado).length} activas · {stations.reduce((n,s)=>n+s.pasajeros_esperando,0)} pasajeros en espera en la red</p><div className="station-grid">{visible.map(s=>{const percent=s.capacidad_maxima?Math.round(s.pasajeros_esperando/s.capacidad_maxima*100):null;return <article className="station-card" key={s.id_estacion}><div className="panel-heading"><span className="eyebrow">{s.codigo}</span><span className={'badge '+(s.estado?'activo':'inactivo')}>{s.estado?'Activa':'Inactiva'}</span></div><h3>{s.nombre}</h3><p><strong>{s.pasajeros_esperando}</strong> pasajeros en espera / {s.capacidad_maxima??'capacidad sin definir'}</p>{percent!==null&&<p className={percent>150?'error':'muted'}>{percent}% del aforo{percent>150?' · Sobrecupo':''}</p>}<ul>{links.filter(l=>l.id_estacion===s.id_estacion).map(l=><li key={l.id_linea}>{lines.find(x=>x.id_linea===l.id_linea)?.nombre??`Línea ${l.id_linea}`} · parada {l.orden} · {l.distancia_anterior_km??0} km desde la anterior</li>)}</ul>{!links.some(l=>l.id_estacion===s.id_estacion)&&<p className="muted">Sin línea asignada</p>}{canCount&&<form className="compact-form" key={`${s.id_estacion}-${s.pasajeros_esperando}`} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save(()=>api(`estaciones/${s.id_estacion}/ocupacion`,'POST',{pasajeros:Number(f.get('pasajeros'))}),'Aforo actualizado.')}}><label>Pasajeros esperando<input name="pasajeros" type="number" min="0" max="100000" step="1" required defaultValue={s.pasajeros_esperando}/></label><button className="secondary" disabled={busy}>Actualizar aforo</button></form>}{admin&&<div className="row-actions"><button className="text-button" onClick={()=>{setEdit(s);setAssign(null)}}>Editar estación</button><button className="text-button" disabled={!s.estado} onClick={()=>{setAssign(s);setEdit(null)}}>Asignar a línea</button></div>}</article>})}</div>{!visible.length&&<p>No hay estaciones que coincidan con la búsqueda.</p>}</>}
 <div className="row-actions station-links"><button className="secondary" onClick={()=>onCatalog('accesos')}>Gestionar accesos</button>{admin&&<button className="secondary" onClick={()=>onCatalog('operador_estacion')}>Asignar operadores</button>}</div>
 </section>
}
