import {useEffect,useState} from 'react';
import {api} from './api';
type Row=Record<string,any>;
export function Users({onPilots}:{onPilots:()=>void}){
 const [rows,setRows]=useState<Row[]>([]),[pilots,setPilots]=useState<Row[]>([]),[edit,setEdit]=useState<Row|null>(null),[role,setRole]=useState('OPERADOR'),[query,setQuery]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 async function load(){const [users,p]=await Promise.all([api('usuarios'),api('catalogos/pilotos')]);setRows(users);setPilots(p)}
 useEffect(()=>{load().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 return <section className="panel management-panel"><div className="panel-heading"><div><h2>Usuarios del sistema</h2><p>Crea accesos y administra las cuentas del personal.</p></div><button className="primary" onClick={()=>{setEdit({});setRole('OPERADOR');setError('');setNotice('')}}>+ Crear usuario</button></div><div className="next-step"><div><strong>Usuarios son cuentas para entrar al sitio</strong><p>Para registrar un conductor o asignarle un bus y una ruta, utiliza Pilotos. No necesita cuenta si no va a iniciar sesión.</p></div><button className="secondary" onClick={onPilots}>Gestionar pilotos →</button></div>{error&&<p className="error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {edit&&<form className="catalog-form" key={edit.id_usuario??'new'} onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setError('');setNotice('');const password=String(form.get('password')??'');try{const data={username:String(form.get('username')).trim(),nombres:String(form.get('nombres')).trim(),...(password?{password}:{})};await api('usuarios'+(edit.id_usuario?'/'+edit.id_usuario:''),edit.id_usuario?'PATCH':'POST',edit.id_usuario?{...data,estado:form.get('estado')==='1'}:{...data,roles:[role],...(role==='PILOTO'?{id_piloto:Number(form.get('id_piloto'))}:{})});await load();setEdit(null);setNotice('Usuario guardado correctamente.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}}><h3>{edit.id_usuario?'Editar cuenta':'Nueva cuenta'}</h3><div className="form-grid"><label>Nombre completo<input name="nombres" required maxLength={100} defaultValue={edit.nombres??''}/></label><label>Nombre de usuario<input name="username" required minLength={3} maxLength={50} autoComplete="off" defaultValue={edit.username??''}/></label><label>{edit.id_usuario?'Nueva contraseña opcional':'Contraseña inicial'}<input name="password" type="password" required={!edit.id_usuario} minLength={12} maxLength={72} autoComplete="new-password"/></label>{edit.id_usuario?<label>Estado<select name="estado" defaultValue={edit.estado?'1':'0'}><option value="1">Activo</option><option value="0">Inactivo</option></select></label>:<label>Rol<select value={role} onChange={e=>setRole(e.target.value)}>{['OPERADOR','SUPERVISOR','SEGURIDAD','FINANCIERO','PILOTO','ADMINISTRADOR'].map(r=><option key={r}>{r}</option>)}</select></label>}{!edit.id_usuario&&role==='PILOTO'&&<label>Piloto vinculado<select name="id_piloto" required defaultValue=""><option value="">Selecciona un piloto disponible…</option>{pilots.filter(p=>p.estado&&!rows.some(u=>u.id_piloto===p.id_piloto)).map(p=><option key={p.id_piloto} value={p.id_piloto}>{p.nombres} {p.apellidos}</option>)}</select></label>}</div>{!edit.id_usuario&&role==='PILOTO'&&!pilots.some(p=>p.estado&&!rows.some(u=>u.id_piloto===p.id_piloto))&&<p role="status">No hay pilotos disponibles para vincular. Registra primero un piloto activo que todavía no tenga cuenta.</p>}<p className="muted">La contraseña requiere al menos 12 caracteres. Al editar, déjala vacía para conservarla. Desactivar impide acceder sin borrar el historial.</p>{edit.id_usuario&&<p>Roles actuales: {edit.usuario_rol.map((r:Row)=>r.roles.nombre).join(', ')}. Esta edición conserva los roles y el piloto vinculado.</p>}<div className="row-actions"><button className="primary" disabled={busy}>{busy?'Guardando…':'Guardar usuario'}</button><button className="secondary" type="button" disabled={busy} onClick={()=>setEdit(null)}>Cancelar</button></div></form>}
 <label>Buscar por nombre o usuario<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Escribe para buscar…"/></label>{loading?<p>Cargando usuarios…</p>:<div className="table-scroll"><table><thead><tr><th>Usuario</th><th>Nombre</th><th>Roles</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{rows.filter(r=>`${r.username} ${r.nombres??''}`.toLowerCase().includes(query.toLowerCase())).map(r=><tr key={r.id_usuario}><td>{r.username}</td><td>{r.nombres}</td><td>{r.usuario_rol.map((x:Row)=>x.roles.nombre).join(', ')}</td><td>{r.estado?'Activo':'Inactivo'}</td><td><button className="text-button" onClick={()=>{setEdit(r);setError('');setNotice('')}}>Editar cuenta</button></td></tr>)}</tbody></table>{!rows.some(r=>`${r.username} ${r.nombres??''}`.toLowerCase().includes(query.toLowerCase()))&&<p>No hay usuarios que coincidan.</p>}</div>}</section>
}
